### ISSUE TITLE
Please choose a license for this project

### ISSUE THREAD

**Issue by Naereen** [mhaz/SCEI-statistics#1]
Hello,
Could you [choose a license](https://choosealicense.com/) and specify if this project is open-source or not?
Unless specified explicitly, a project stays closed-source, even if the files are on GitHub, see [this explanation](https://choosealicense.com/no-permission/).
Thanks in advance!
Regards, -- @Naereen

**Comment by mhaz** [comment]
Hi,
Yes, as far as I am concerned, I have no opposition making this project open-source.
I am gathering the data from https://www.scei-concours.fr/statistiques.php without a formal authorization. Since I am not the original author of the data nor the owner, I am not sure if I'm allowed to single-handedly decide on a license for the data itself.

Regarding my contributions, the GPL license fits my idea of the project. 
Do you know if I'm allowed to declare this project to be distributed under the GPL license although it contains data scrapped from online resources?

**Comment by Naereen** [comment]
Hi, (on peut continuer en français si tu préfères)

Of course you have no right to distribute the data here and even less right to add a license to it!
But the README file could state something like:

The code is licensed under (GPL License - or anyother) but the data is © SCEI and was scrapped on (DATE). It is not my property, and it is stored here for archive and research purpose. I will delete it if SCEI asks.

(nobody will never ask, nobody cares... and even if they do, you can just delete in a commit... and the old commits will keep the data, except if you rewrite all the git history)

**Comment by mhaz** [comment]
Je vais ajouter ton commentaire en pied de page du README.
Si je ne suis pas autorise a garder une copie des donnees en local dans le repo, une alternative peut etre de demander au script de telecharger l'`html` a chaque fois. Ou de remplacer les fichiers par un script qui les telecharge et indiquer aux curieux de les telecharger eux-meme.

**Comment by Naereen** [comment]
Chouette !

Je pense qu'il n'y a pas de raison de supprimer quoi que ce soit, mais peut-être que quelqu'un le demandera un jour.

**Comment by Naereen** [comment]
Et il vaut mieux garder les données, puisqu'elles seront probablement supprimées du site !

Je ne les ai pas proprement mises dans un dossier à part, mais je garde une archive des résultats du concours de l'agrégation de mathématiques, ici [pour les HTML](https://perso.crans.org/besson/notebooks/agreg/TP_SQL/donnees_html/) et [pour les CSV](https://perso.crans.org/besson/notebooks/agreg/TP_SQL/donnees_html/) (c'est [dans ce projet GitHub](https://github.com/Naereen/notebooks/tree/master/agreg/TP_SQL/))...
